# Generated by Django 3.2.6 on 2021-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Level', models.CharField(max_length=20)),
                ('Pro', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
    ]
