# Generated by Django 3.2.6 on 2021-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Content',
            field=models.TextField(),
        ),
    ]
