# Generated by Django 3.2.6 on 2021-10-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
